.PRONY: dev-dependencies
dev-dependencies:
	cd ../hub-integration && make dev && \
	cd ../hub-extension-back && make dev && \
	cd ../hub-data && make dev && \
	cd ../driven-time

.PRONY: dev-dependencies
dev-dependencies-down:
	cd ../hub-integration && make dev-down && \
	cd ../hub-extension-back && make dev-down && \
	cd ../hub-data && make dev-down && \
	cd ../driven-time


